export const metadata = {
  title: "Movie App",
  description: "Generated by Next.js",
};
import "./globals.css";
import Header from "../components/Header";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
