export const metadata = {
  title: "Movie App",
  description: "Generated by Next.js",
};
import "./globals.css";
import Header from "../components/Header";
import Providers from "./Providers";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
